services:
  bonus_nginx:
    build:
      context: ./contexts/bonus_nginx
    container_name: bonus_nginx
    #restart: always
    env_file:
      - .env
    networks:
      - incep

networks:
  incep:
    driver: bridge