#version: '3.8'

services:
# 1-1.mariadb
  mariadb:
    build:
      context: ./contexts/mariadb
    container_name: mariadb
    #restart: always
    env_file:
      - .env
    secrets:
      - mariadb_root_password
      - mariadb_user_password
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - incep

# 1-2.wordpress
  wordpress:
    build:
      context: ./contexts/wordpress
    container_name: wordpress
    #restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    secrets:
      - mariadb_user_password
      - wp_admin_password
      - wp_user_password
    volumes: 
      - wordpress_vol:/var/www/html:rw
    networks:
      - incep

# 1-3.nginx
  nginx:
    build:
      context: ./contexts/nginx
    container_name: nginx
    #restart: always
    depends_on:
      - wordpress
    env_file:
      - .env
    volumes:
      - wordpress_vol:/var/www/html:rw
    networks:
      - incep
    ports:
      - "443:443"

networks:
  incep:
    driver: bridge

volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/repri/data/mariadb'
  wordpress_vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/repri/data/wordpress'

secrets:
  mariadb_root_password:
    file: ../secrets/db_root_password.txt
  mariadb_user_password:
    file: ../secrets/db_user_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
